In [1]:
import numpy as np
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a1,a2,a3)

print(a3.shape) 
print(a3.ndim)
print(a2.size)
print(a3.itemsize)

[0 1 2 3 4 5 6 7 8 9] [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]] [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
(2, 2, 2)
3
12
8


In [2]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)