In [11]:
import numpy as np
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[42., 11., 89.],
       [ 3., 22., 56.],
       [72.,  6., 93.]])

In [12]:
np.min

<function min at 0x000002171A5862B0>

In [13]:
a1.max

<function ndarray.max(axis=None, out=None, **kwargs)>

In [14]:
a1.max()

np.float64(93.0)

In [15]:
a1.prod()

np.float64(6105632214528.0)

In [16]:
a1.min()

np.float64(3.0)

In [19]:
a1.max(axis=1)

array([89., 56., 93.])

In [20]:
np.max(a1,axis=0)

array([72., 22., 93.])

In [21]:
np.mean(a1,axis=1)

array([47.33333333, 27.        , 57.        ])

In [22]:
np.mean(a1,axis=0)

array([39.        , 13.        , 79.33333333])

In [23]:
a1.mean(axis=1)

array([47.33333333, 27.        , 57.        ])

In [24]:
a1.var(axis=1)

array([1028.22222222,  480.66666667, 1374.        ])

In [25]:
a1.min(axis=0)

array([ 3.,  6., 56.])

In [26]:
#dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

In [27]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [29]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [30]:
np.log(a2)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_13288\970536687.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a2)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [31]:
np.exp(a1)

array([[1.73927494e+18, 5.98741417e+04, 4.48961282e+38],
       [2.00855369e+01, 3.58491285e+09, 2.09165950e+24],
       [1.85867175e+31, 4.03428793e+02, 2.45124554e+40]])

In [32]:
#round,floor,ceil
np.round(np.random.random((2,3))*100)

array([[81., 91., 37.],
       [77., 50., 87.]])